ARRAY_ACTIONS

In [1]:
import numpy as np

from numpy import linspace

In [2]:
arr1 = np.arange(8)
arr2 = np.arange(16)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

chnaging the shape of array

In [3]:
arr1.shape = (2,4)
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

we get and error if we cant reshape

In [4]:
arr2.shape = (2,7)

ValueError: cannot reshape array of size 16 into shape (2,7)

creating new arraw from old without amended the first one

In [ ]:
arr2_new = arr2.reshape((2,8))
arr2_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

Direct how to reshape by lines or columns

In [ ]:
arr2_newF = arr2.reshape((2,8), order='F')
arr2_newF

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

Changing columns and lines for 2d arrays

In [ ]:
newArr = np.arange(16)
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
newArr.shape = (2,8)
newArr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
newArr_traspose = newArr.transpose()
newArr_traspose

array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

### Array - indexes and slices

In [ ]:
na = linspace(1,2,6)
na

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [ ]:
print(na[2])

1.4


In [ ]:
print(na[2:5])

[1.4 1.6 1.8]


In [ ]:
print(na[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


easy way to create dn-array from one-dimentional

In [ ]:
nAr = linspace(0,6,12, endpoint=False).reshape(3,4)
nAr

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Its easy to addres in Numpy to index

usual way

In [ ]:
print(nAr[1][2])

3.0


in numpy

In [ ]:
print(nAr[1,2])

3.0


it's also true abour slicing it's much easy to address

In [ ]:
nAr[:2,1]

array([0.5, 2.5])

In [ ]:
nAr[1:,2:4]

array([[3. , 3.5],
       [5. , 5.5]])

all lines for example for columns specifyed

In [ ]:
nAr[:,2:4]


array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

all colums in lines specified

In [ ]:
nAr[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

## Example

In [6]:
test_arr = np.arange(50, dtype=np.int8).reshape(5,10)
test_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]], dtype=int8)

In [ ]:
n1 = test_arr[4,2]
print(n1)

42


In [ ]:
l = test_arr[-1,-1]
print(l)

49


In [ ]:
line = test_arr[3]
print(line)

[30 31 32 33 34 35 36 37 38 39]


In [ ]:
column = test_arr[:,-2]
print(column)

[ 8 18 28 38 48]


In [7]:
minarr = test_arr[1:4, 2:5]
minarr

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]], dtype=int8)

In [25]:

rever1 = test_arr[:,-1]
rever2 = rever1[::-1]
rever2

array([49, 39, 29, 19,  9], dtype=int8)

In [32]:
#rever1 = test_arr[:,-1] [:, 1::-1]
rever3[:, -1] = test_arr[:, 1::-1]
rever3

ValueError: could not broadcast input array from shape (5,2) into shape (0,)

In [ ]:
transp = np.transpose(test_arr)
transp

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]], dtype=int8)

## TEST tasks

import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

In [ ]:
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

## Sorting arrays

numby.sort() return a new array

In [40]:
arr = np.array([23,12,45,12,23,4,15,3],dtype=np.int8)

arr_sor = np.sort(arr)

arr_sor

array([ 3,  4, 12, 12, 15, 23, 23, 45], dtype=int8)

In [38]:
arr3 = np.array([23,12,45,12,23,4,15,3])

arr3.sort()

arr3



array([ 3,  4, 12, 12, 15, 23, 23, 45])

In [43]:
arr.dtype

dtype('int8')

MISSING DATA

In [44]:
sArr = np.sqrt([4, 9, -4, 3])
sArr

C:\Users\John Lee\AppData\Local\Temp\ipykernel_11168\653639906.py:1: RuntimeWarning: invalid value encountered in sqrt
  sArr = np.sqrt([4, 9, -4, 3])


array([2.        , 3.        ,        nan, 1.73205081])

In [45]:
sArr[2]

nan

In [46]:
print(type(None))

<class 'NoneType'>


In [47]:
print(type(np.nan))

<class 'float'>


In [48]:
np.isnan(sArr)

array([False, False,  True, False])

In [49]:
sum(sArr)

nan

In [51]:
roots = sArr

roots[np.isnan(sArr)] = 0

In [52]:
print(roots)

[2.         3.         0.         1.73205081]


In [53]:
sum(roots)

6.732050807568877