In [4]:
import numpy as np

In [5]:
array = np.array([1,3,5,6,7,9])

In [6]:
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 3 5 6 7 9]


In [7]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


How to find what type data is stored inside array

In [9]:
print(ndarray.dtype)

int32


We can set the dta types when initializing the array

In [10]:
arr_3 = np.array([1,2,3,4,5,6], dtype = np.int8)
arr_3   

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [11]:
arr_3[2] = 7
arr_3

array([1, 2, 7, 4, 5, 6], dtype=int8)

In [12]:
arr_5 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
arr_5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [13]:
arr_5 [0][1] = 7
arr_5

array([[1, 7, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

if we want to put there something biger type we got an error. number will be cut off

In [14]:
arr_5[1][2] = 500
arr_5

array([[  1,   7,   3],
       [  4,   5, -12],
       [  7,   8,   9]], dtype=int8)

float has lost digit after dot

In [15]:
arr_3[0] = 12.5
arr_3

array([12,  2,  7,  4,  5,  6], dtype=int8)

number from str will be converted automative 

In [16]:
arr_3[3] = '15'
arr_3

array([12,  2,  7, 15,  5,  6], dtype=int8)

however if it is string we get en error

In [17]:
arr_3[4] = 'str'

ValueError: invalid literal for int() with base 10: 'str'

we can change array type

In [ ]:
arr_3

array([12,  2,  7, 15,  5,  6], dtype=int8)

In [ ]:
arr_3 = np.int64(arr_3)

arr_3

array([12,  2,  7, 15,  5,  6], dtype=int64)

howerver we can loose some data as usual if we converted to a smalle data type

In [ ]:
arr_6 = np.array([3434,55,656,767,35535], dtype=np.int64)
arr_6

array([ 3434,    55,   656,   767, 35535], dtype=int64)

In [ ]:
arr_6 = np.int8(arr_6)
arr_6

array([ 106,   55, -112,   -1,  -49], dtype=int8)

### Example -  cretaing array wich can hold the data

In [ ]:
arr_test = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr_test

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

### Array features

In [18]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

we can find out the dimentions of array by following command

In [ ]:
arr.ndim

1

In [ ]:
nd_arr.ndim

2

Size will show all count of array in library

In [ ]:
arr.size

5

In [ ]:
nd_arr.size

9

shape will reveal the whole stracture of array

In [ ]:
arr.shape

(5,)

In [ ]:
nd_arr.shape

(3, 3)

Size of array we could find by itemsize. it shows in byte

In [19]:
arr.itemsize

1

In [20]:
nd_arr.itemsize

2

Creating empty arrays


In [22]:
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [25]:
zero_3d = np.zeros((3,2,5), dtype=np.int8)
zero_3d.shape

(3, 2, 5)

In [26]:
zero_3d

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

In [29]:
zero_2d =  np.zeros((3,5), dtype = np.int8)

In [30]:
zero_2d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### arange

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(3.5,7)

array([3.5, 4.5, 5.5, 6.5])

In [38]:
np.arange(3.5,7,0.25, dtype = np.float16)

array([3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  ,
       6.25, 6.5 , 6.75], dtype=float16)

Linear space

In [39]:
lar = np.linspace(1,2,10)
lar

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [40]:
np.linspace(1,2,20, endpoint=False, dtype = np.float64)

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95])

Linear space returns also step

In [45]:
lar2, step = np.linspace(1,2,10, retstep = True, dtype = np.float16)
print(step)

0.1111111111111111


In [47]:
lar2, step = np.linspace(1,2,10, endpoint=False, retstep = True, dtype = np.float16)
print(step)

0.1


In [48]:
print(lar2)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? Ответ округлите до двух знаков после точки.

In [51]:
lrd3,step2 = np.linspace(-6,21,60, endpoint=False, retstep=True)

In [52]:
print(round(step2,2))

0.45
