In [9]:
import numpy as np

In [10]:
array = np.array([1,3,5,6,7,9])

In [11]:
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 3 5 6 7 9]


In [12]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


How to find what type data is stored inside array

In [14]:
print(ndarray.dtype)

int32


We can set the dta types when initializing the array

In [18]:
arr_3 = np.array([1,2,3,4,5,6], dtype = np.int8)
arr_3   

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [19]:
arr_3[2] = 7
arr_3

array([1, 2, 7, 4, 5, 6], dtype=int8)

In [21]:
arr_5 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
arr_5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [22]:
arr_5 [0][1] = 7
arr_5

array([[1, 7, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

if we want to put there something biger type we got an error. number will be cut off

In [23]:
arr_5[1][2] = 500
arr_5

array([[  1,   7,   3],
       [  4,   5, -12],
       [  7,   8,   9]], dtype=int8)

float has lost digit after dot

In [24]:
arr_3[0] = 12.5
arr_3

array([12,  2,  7,  4,  5,  6], dtype=int8)

number from str will be converted automative 

In [25]:
arr_3[3] = '15'
arr_3

array([12,  2,  7, 15,  5,  6], dtype=int8)

however if it is string we get en error

In [26]:
arr_3[4] = 'str'

ValueError: invalid literal for int() with base 10: 'str'

we can change array type

In [27]:
arr_3

array([12,  2,  7, 15,  5,  6], dtype=int8)

In [30]:
arr_3 = np.int64(arr_3)

arr_3

array([12,  2,  7, 15,  5,  6], dtype=int64)

howerver we can loose some data as usual if we converted to a smalle data type

In [36]:
arr_6 = np.array([3434,55,656,767,35535], dtype=np.int64)
arr_6

array([ 3434,    55,   656,   767, 35535], dtype=int64)

In [37]:
arr_6 = np.int8(arr_6)
arr_6

array([ 106,   55, -112,   -1,  -49], dtype=int8)

### Example -  cretaing array wich can hold the data

In [40]:
arr_test = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr_test

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

### Array features

In [42]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

we can find out the dimentions of array by following command

In [43]:
arr.ndim

1

In [44]:
nd_arr.ndim

2

Size will show all count of array in library

In [45]:
arr.size

5

In [46]:
nd_arr.size

9

shape will reveal the whole stracture of array

In [47]:
arr.shape

(5,)

In [48]:
nd_arr.shape

(3, 3)

Yes