In [1]:
import numpy as np

In [2]:
array = np.array([1,3,5,6,7,9])

In [4]:
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 3 5 6 7 9]


In [7]:
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


How to find what type data is stored inside array

In [10]:
print(ndarray.dtype)

int32
