## Vectror

summering two vector

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

if we summering two list.its simple adding one to the other

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

For the lists we have to write a function using zip

In [3]:
[x + y for x,y in zip(list1,list2)]

[14, 10, 10.6, 15.5]

Multiplying two vectors. We can multyply two vectrors only the same size

In [4]:
vec1*vec2

array([24. , 24. , 25.2, 32.5])

Howeever this rule doesn't apply for one element operation

In [5]:
vec = np.arange(5)

vec*5


array([ 0,  5, 10, 15, 20])

In [6]:
vec**2

array([ 0,  1,  4,  9, 16])

We can also compare one vect to another , and with one number

In [7]:
vec3 = vec1>vec2
vec3

array([False, False,  True, False])

In [8]:
vec5 = vec1>6

vec5

array([False, False,  True, False])

### Vector features

In [9]:
vecl = np.array([3,4])

long path to find vector length

In [10]:
length = np.sqrt(sum(vecl**2))
print(length)

5.0


we use shorter path from liner alghr modul

In [11]:
length2 = np.linalg.norm(vecl)
length2

5.0

long path to find distance between two vectors

In [13]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])

dist = np.sqrt(sum((vec1-vec2)**2))

dist

12.206555615733702

Now with help of norm function

In [16]:
dist2 = np.linalg.norm(vec1-vec2)
dist2

12.206555615733702

scalar operation

In [21]:
vec7 = np.arange(1, 6)
vec8 = np.linspace(10, 20, 5)

In [22]:
scalar_product = np.sum(vec7*vec8)
scalar_product

250.0

much easy way to find scalar. its indicate the angle between two vectors.

In [24]:
np.dot(vec7,vec8)

250.0

In [25]:
#vectror is percpendicular is scalar o
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

## TEST TASK

In [26]:
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

find co-directional vectors

In [28]:
pair1 = a+b
pair1

array([-31,  35,  73])

In [29]:
length_sum_pair1 = np.linalg.norm(pair1)
length_sum_pair1

86.68909966079934

In [32]:
sum_length_pair1 = np.linalg.norm(a) + np.linalg.norm(b)

In [33]:
sum_length_pair1

120.07611358830478

In [37]:
def co_vectors_checking(a,b,c):
    if round(np.linalg.norm(a-b), 2) > 100:
        print('Distance between  vector {} and vector {} is higher than 100'.format("a", "b"))
    elif round(np.linalg.norm(a-c), 2) > 100:
        print('Distance between  vector {} and vector {} is higher than 100'.format("a", "c"))
    elif round(np.linalg.norm(b-c), 2) > 100:
        print('Distance between  vector {} and vector {} is higher than 100'.format("b", "c"))
    else:
        print("such pair doesn't exist")
    

In [41]:
co_vectors_checking(a,b,c)

Distance between  vector b and vector c is higher than 100


In [36]:
co_vectors_checking(a,b,c)

Vector [23 34 27] and vector [46 68 54] is co-directional


In [42]:
np.dot(a,b)

34

In [43]:
np.dot(b,c)

68

In [44]:
np.dot(c,b)

68

## Static methiods

In [45]:
vec = np.array([2,7,18,28,18,1,8,4])

In [47]:
vec.max()

28

In [48]:
np.min(vec)

1

In [49]:
vec.mean()

10.75

In [50]:
np.median(vec)

7.5

In [51]:
np.std(vec)

8.954747344286158

In [52]:
simplelist = [19, 242, 14, 152, 142, 1000]

sl = np.array(simplelist)

sl.mean()

261.5